# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

blocks:
- type: prompt
  alignment: left
  segments:
  - template: ╭─
    foreground: "#585858"
    type: text
    style: plain
  - template: " {{ if .WSL }}WSL at {{ end }}\uF303 "
    foreground: "#26C6DA"
    background: "#303030"
    type: os
    style: plain
  - template: 
    foreground: "#8a8a8a"
    background: parentBackground
    type: text
    style: plain
  - template: " {{ if eq .PWD \"~\" }}\uf015 {{ else }}\uf07c {{ end }}{{ .Parent }}"
    foreground: "#0087af"
    background: parentBackground
    type: path
    style: plain
  - properties:
      style: folder
    template: "<b>{{ .Path }}</b> "
    foreground: "#00afff"
    background: parentBackground
    type: path
    style: plain
  - properties:
      branch_icon: <b> </b>
      fetch_status: true
      fetch_upstream_icon: true
      git_icon: "\uf1d3 "
      github_icon: "\uf09b "
      gitlab_icon: "\uf296 "
    template: "<#8a8a8a>\ue0b1</> {{ if .UpstreamIcon}}{{ .UpstreamIcon }}{{ else }}\uf1d3 {{ end }}{{ .HEAD }}{{ if .Working.Changed }} <#00afff>{{ .Working.String }}</>{{ end }} "
    foreground: "#5fd700"
    background: parentBackground
    type: git
    style: plain
  - template: 
    foreground: parentBackground
    background: transparent
    type: text
    style: plain
  newline: true
- type: prompt
  alignment: right
  filler: "<#585858>-</>"
  segments:
  - template: 
    foreground: parentForeground
    background: transparent
    type: text
    style: plain
  - properties:
      always_enabled: true
      status_template: "{{ if eq .Code 130 }}INT{{ else if .eq Code 131}}QUIT{{ else if eq .Code 137 }}KILL{{ end }}"
    template: " {{ if eq .Code 0 }}<#5faf00>✔</>{{ else }}{{.String}} ✘{{ end }}"
    foreground: "#d70000"
    background: parentForeground
    type: status
    style: plain
  - properties:
      display_mode: environment
      default_venv_names:
      - env
      - .env
      fetch_virtual_env: true
    template: " <#8a8a8a>\ue0b3</> {{ .Venv }} \ue73c"
    foreground: "#00afaf"
    background: parentBackground
    type: python
    style: plain
  - properties:
      style: round
      threshold: 5000
    template: " <#8a8a8a>\ue0b3</> {{ .FormattedMs }} \uf252"
    foreground: "#a8a8a8"
    background: parentBackground
    type: executiontime
    style: plain
  - template: "{{ if .SSHSession }} <#8a8a8a>\ue0b3</> {{ .UserName }}@{{ .HostName }}{{ end }}"
    foreground: "#d7af87"
    background: parentBackground
    type: session
    style: plain
  - properties:
      time_format: "15:04:05"
    template: " <#8a8a8a>\ue0b3</> {{ .CurrentDate | date .Format }} \uf017 "
    foreground: "#5f8787"
    background: parentBackground
    type: time
    style: plain
  - template: ─╮
    foreground: "#585858"
    background: transparent
    type: text
    style: plain
- type: prompt
  alignment: left
  segments:
  - template: "╰─ "
    foreground: "#585858"
    type: text
    style: plain
  newline: true
- type: rprompt
  segments:
  - template: ─╯
    foreground: "#585858"
    type: text
    style: plain
version: 3
